// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCMZaUpgOhsWVOmFndkEXfLw7XTHEK-jg',
    appId: '1:646075973253:web:1092082881f9fd6cf2f3ec',
    messagingSenderId: '646075973253',
    projectId: 'chat-app-e85f8',
    authDomain: 'chat-app-e85f8.firebaseapp.com',
    storageBucket: 'chat-app-e85f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsO2UcVy4cqLF95MTPxW_0pJsSWmREKTE',
    appId: '1:646075973253:android:b337b9d02b907728f2f3ec',
    messagingSenderId: '646075973253',
    projectId: 'chat-app-e85f8',
    storageBucket: 'chat-app-e85f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNp5GgQaoguSNw5bNMH5jYN_FWCBlfeDc',
    appId: '1:646075973253:ios:996483d835657278f2f3ec',
    messagingSenderId: '646075973253',
    projectId: 'chat-app-e85f8',
    storageBucket: 'chat-app-e85f8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNp5GgQaoguSNw5bNMH5jYN_FWCBlfeDc',
    appId: '1:646075973253:ios:371642580c149ac0f2f3ec',
    messagingSenderId: '646075973253',
    projectId: 'chat-app-e85f8',
    storageBucket: 'chat-app-e85f8.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
